# Generated by Django 4.1.1 on 2022-10-04 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_alter_candidate_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Photo',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
