# Generated by Django 4.1.1 on 2022-10-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Expirience',
            field=models.TextField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='middle'),
        ),
    ]
