# Generated by Django 4.1.1 on 2022-09-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.TextField(max_length=20)),
                ('Location', models.TextField(verbose_name=[('Moscow', 'Moscow'), ('Perm', 'Perm'), ('London', 'London')])),
                ('Category', models.TextField(verbose_name=[('Category1', 'Category1'), ('Category2', 'Category2'), ('Category3', 'Category3')])),
                ('Requests', models.PositiveBigIntegerField()),
            ],
        ),
    ]
