# Generated by Django 4.1.1 on 2022-09-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Type',
            field=models.TextField(db_index=True, max_length=20),
        ),
    ]
