# Generated by Django 4.1.1 on 2022-10-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_alter_work_requests_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='Type',
        ),
        migrations.AddField(
            model_name='company',
            name='Symbol',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='job',
            name='IsOnMain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='Name',
            field=models.TextField(default='unknown'),
        ),
        migrations.AlterField(
            model_name='company',
            name='Rating',
            field=models.IntegerField(choices=[(1, 'Awful'), (2, 'Bad'), (3, 'Better'), (4, 'Good'), (5, 'Best')], default=0),
        ),
        migrations.RemoveField(
            model_name='job',
            name='Company',
        ),
        migrations.RemoveField(
            model_name='job',
            name='Work_data',
        ),
        migrations.AddField(
            model_name='job',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
        migrations.AddField(
            model_name='job',
            name='Work_data',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.work'),
        ),
    ]
