# Generated by Django 4.1.1 on 2022-10-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_remove_work_type_company_symbol_job_isonmain_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Symbol',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='work',
            name='Category',
            field=models.TextField(verbose_name=[('Design & Creative', 'Design'), ('Marketing', 'Marketing'), ('Telemarketing', 'Telemarketing'), ('Software & Web', 'Software'), ('Administration', 'Administration'), ('Teaching & Education', 'Teaching'), ('Engineering', 'Engineering'), ('Textile', 'Textile')]),
        ),
    ]
