# Generated by Django 4.1.1 on 2022-10-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_company_symbol_alter_work_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Category',
            field=models.IntegerField(verbose_name=[(1, 'Design'), (2, 'Marketing'), (3, 'Telemarketing'), (4, 'Software'), (5, 'Administration'), (6, 'Teaching'), (7, 'Engineering'), (8, 'Textile')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='Location',
            field=models.IntegerField(verbose_name=[(1, 'Moscow'), (2, 'Perm'), (3, 'London')]),
        ),
    ]
