# Generated by Django 4.1.1 on 2022-10-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_work_category_alter_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Category',
            field=models.TextField(choices=[('Design & Creative', 'Design'), ('Marketing', 'Marketing'), ('Telemarketing', 'Telemarketing'), ('Software & Web', 'Software'), ('Administration', 'Administration'), ('Teaching & Education', 'Teaching'), ('Engineering', 'Engineering'), ('Textile', 'Textile')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='Location',
            field=models.TextField(choices=[('Moscow', 'Moscow'), ('Perm', 'Perm'), ('London', 'London')]),
        ),
    ]
