# Generated by Django 4.1.1 on 2022-10-01 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_alter_job_qualifications_alter_job_responsibilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(default='unnamed', max_length=50)),
                ('Requests', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='Requests',
        ),
        migrations.AlterField(
            model_name='work',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.category'),
        ),
    ]
