# Generated by Django 4.1.1 on 2022-10-01 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_location_alter_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name',
            field=models.TextField(default='unnamed', max_length=50, unique=True),
        ),
    ]
