# Generated by Django 4.1.1 on 2022-10-01 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Work_data',
        ),
        migrations.AddField(
            model_name='job',
            name='Category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.category'),
        ),
        migrations.AddField(
            model_name='job',
            name='Location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.location'),
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
