# Generated by Django 4.1.1 on 2022-10-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_remove_job_work_data_job_category_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='AvalibleJob',
            field=models.IntegerField(default=0),
        ),
    ]
