# Generated by Django 4.1.1 on 2022-10-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_alter_company_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Exp',
            field=models.TextField(choices=[('junior', 'Junior'), ('middle', 'Middle'), ('senior', 'Senior')], default='junior'),
        ),
    ]
