# Generated by Django 4.1.1 on 2022-10-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_alter_job_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='CNN',
            field=models.TextField(default='hi'),
        ),
        migrations.AddField(
            model_name='company',
            name='SomeInfo',
            field=models.TextField(default='hello'),
        ),
    ]
