# Generated by Django 4.1.1 on 2022-10-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_cnn_company_someinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Symbol',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
