# Generated by Django 4.1.1 on 2022-10-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_alter_company_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Symbol',
            field=models.ImageField(default='hello', upload_to='static/media'),
        ),
    ]
