# Generated by Django 4.1.1 on 2022-10-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_company_cnn_company_someinfo'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='CNN',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='SomeInfo',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='company',
            field=models.OneToOneField(default=5, on_delete=django.db.models.deletion.CASCADE, to='companies.company'),
        ),
    ]
