# Generated by Django 4.1.1 on 2022-10-03 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Auth', '0007_averageuser_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='averageuser',
            name='CandidateId',
        ),
        migrations.AddField(
            model_name='averageuser',
            name='Candidate',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate'),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='Liked',
            field=models.ManyToManyField(to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='averageuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
