# Generated by Django 4.1.1 on 2022-10-03 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('candidates', '0001_initial'),
        ('companies', '0024_alter_company_symbol'),
        ('Auth', '0008_remove_averageuser_candidateid_averageuser_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averageuser',
            name='Candidate',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='candidates.candidate'),
        ),
        migrations.AlterField(
            model_name='averageuser',
            name='Liked',
            field=models.ManyToManyField(blank=True, null=True, to='companies.job'),
        ),
        migrations.AlterField(
            model_name='averageuser',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
