# Generated by Django 4.1.1 on 2022-10-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_alter_company_symbol'),
        ('Auth', '0009_alter_averageuser_candidate_alter_averageuser_liked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='Responses',
            field=models.ManyToManyField(to='companies.job'),
        ),
    ]
