# Generated by Django 4.1.1 on 2022-10-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0028_alter_company_symbol'),
        ('Auth', '0010_companyuser_responses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='Responses',
        ),
        migrations.AddField(
            model_name='averageuser',
            name='Responses',
            field=models.ManyToManyField(related_name='responses', to='companies.job'),
        ),
    ]
