# Generated by Django 4.1.1 on 2022-10-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField(max_length=100)),
                ('Surname', models.TextField(max_length=100)),
                ('Education', models.TextField(choices=[('elementary', 'Elementary'), ('school', 'School'), ('university', 'University')])),
                ('Resume', models.FileField(upload_to='static/files')),
                ('Mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
