# Generated by Django 4.1.1 on 2022-10-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='Education',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Mail',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Resume',
        ),
    ]
