# Generated by Django 4.1.1 on 2022-10-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Position',
            field=models.TextField(null=True),
        ),
    ]
