# Generated by Django 4.1.1 on 2022-10-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Photo',
            field=models.ImageField(null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='Resume',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
