# Generated by Django 4.1.1 on 2022-10-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_photo_alter_candidate_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ShortInfo',
            field=models.TextField(null=True),
        ),
    ]
