# Generated by Django 4.1.1 on 2022-10-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0007_candidate_shortinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='Qualifications',
            field=models.TextField(null=True),
        ),
    ]
