# Generated by Django 4.1.1 on 2022-10-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_candidate_user'),
    ]

    operations = [

    ]
