# Generated by Django 4.1.1 on 2022-10-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_remove_candidate_user_candidate_isactive'),
    ]

    operations = [

    ]
