# Generated by Django 4.1.1 on 2022-10-03 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0011_candidate_isactive'),
    ]

    operations = [

    ]
